### ISSUE TITLE
fail to read a file with deno

### ISSUE THREAD

**Issue by sigmaSd** [wasmerio/wasmer-js#321]
## Steps to reproduce

- mkdir f; cd f
- cargo new a
- echo "hello">file
- echo 'fn main() {dbg!(std::fs::read_to_string("./file"));}'>a/src/main.rs
- cargo b --manifest-path a/Cargo.toml --target-dir target --target wasm32-wasi
- wasmer target/wasm32-wasi/debug/a.wasm --dir . # works, same  for wasmtime

```typescript
import { init, WASI } from "https://deno.land/x/wasm@v1.2.2/wasi.ts";
await init();

const wasi = new WASI({});

const moduleBytes = await Deno.readFile(
  "./target/wasm32-wasi/debug/a.wasm",
);
const module = await WebAssembly.compile(moduleBytes);
wasi.instantiate(module, {});

const exitCode = wasi.start();
const stdout = wasi.getStdoutString();
const stderr = wasi.getStderrString();
console.log(`${stdout}${stderr}(exit code: ${exitCode})`);
```
fails with 
```
[src/main.rs:1] std::fs::read_to_string("./file") = Err(
    Os {
        code: 44,
        kind: NotFound,
        message: "No such file or directory",
    },
)
(exit code: 0)
```

**Comment by sigmaSd** [comment]
deno wasi implementation have its own issue https://github.com/denoland/deno_std/issues/3415

**Comment by sigmaSd** [comment]
So thats probably it I need to use 
```
const wasi = new WASI({ preopens: { ".": "." } });
```

but this fails
```
error: Uncaught (in promise) Error: Failed to create the WasiState: wasi filesystem creation error: `Could not get metadata for fil
e ".": fd not a directory``
        const ret = new Error(getStringFromWasm0(arg0, arg1));
                    ^
    at imports.wbg.__wbg_new_8d2af00bc1e329ee (https://deno.land/x/wasm@v1.2.2/pkg/wasmer_wasi_js.js:1185:21)
    at <anonymous> (https://deno.land/x/wasm@v1.2.2/pkg/wasmer_wasi_js_bg.wasm:1:19665)
    at new WASI (https://deno.land/x/wasm@v1.2.2/pkg/wasmer_wasi_js.js:632:18)
    at file:///home/mrcool/dev/deno/lab/tmp/xiU/b.ts:4:14
    at eventLoopTick (ext:core/01_core.js:182:11)
```

using deno std implementation (https://deno.land/std@0.190.0/wasi/snapshot_preview1.ts) works so this maybe a wasmerjs issue

**Comment by jeff-hykin** [comment]
Here's a temp workaround for deno:

```js
import { WasmFs } from "@wasmer/wasmfs"
// pretty hacky but works
Uint8Array.prototype.write = (string, encoding)=>new TextEncoder(encoding).encode(string)
const wasmFs = new WasmFs()
```

**Comment by sigmaSd** [comment]
@jeff-hykin you don't need that hack instead you can just use `-unstable-unsafe-proto` `deno run --unstable-unsafe-proto a.ts`

**Comment by jeff-hykin** [comment]
Cool I didnt know those existed. 

That said, I'm making a library and I wouldnt want library users to need to add that flag to their runtime.

I ended up forking the dependency and getting rid of the proto usage that way. Its pretty much all from node Buffer shims.

**Comment by talentlessguy** [comment]
the workaround didn't work for me:

```js
import { init, WASI } from "@wasmer/wasi";
import fs from "node:fs/promises";

await init();

Object.defineProperty(Object.getPrototypeOf({}), "__proto__", {
  get() {
    return Object.getPrototypeOf(this);
  },
  set(value) {
    return Object.setPrototypeOf(this, value);
  },
});

export const setupSolar = async (args = []) => {
  let output = "";
  const wasi = new WASI({
    args,
    preopens: {
      ".": ".",
    },
  });
  const bytes = await fs.readFile("./solar.wasm");
  const { instance } = await WebAssembly.instantiate(bytes, {
    wasi_snapshot_preview1: wasi.wasiImport,
  });

  wasi.start(instance);
  return { output };
};

await setupSolar(["-j1", "./Counter.sol", "--emit", "abi"]);
```

I'm hitting a different kind of error:

```
error: Uncaught (in promise) Error: Failed to create the WasiState: wasi filesystem creation error: `Could not get metadata for file ".": fd not a directory``
```
