### ISSUE TITLE
Is Deno still supported in the new sdk

### ISSUE THREAD

**Issue by sigmaSd** [wasmerio/wasmer-js#340]
```ts
import * as wasm from "https://deno.land/x/wasm@wasmer-sdk-v0.2.0/lib.ts";
```
```
error: Relative import path "buffer" not prefixed with / or ./ or ../
If you want to use a built-in Node module, add a "node:" prefix (ex. "node:buffer").
    at https://deno.land/x/wasm@wasmer-sdk-v0.2.0/lib.ts:1:24
```

**Comment by syrusakbary** [comment]
We have not taken a look yet (it's the early days of the SDK), but we'd love to support Deno on the Wasmer JS SDK as well!

**Comment by sigmaSd** [comment]
cool! just for reference wasmpack does support deno as a target, so maybe its not that hard to add it back

**Comment by sigmaSd** [comment]
Using deno npm compat, also doesn't work
```ts
import * as wasm from "npm:@wasmer/sdk";
await wasm.init();
```
```
error: Uncaught (in promise) TypeError: A.write is not a function
    at file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/@wasmer/sdk/0.4.1/dist/Library.cjs:11:4377
    at a (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/@wasmer/sdk/0.4.1/dist/Library.cjs:11:4421)
    at Function.K.from (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/@wasmer/sdk/0.4.1/dist/Library.cjs:11:9346)
    at XA (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/@wasmer/sdk/0.4.1/dist/Library.cjs:11:54506)
    at file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/@wasmer/sdk/0.4.1/dist/Library.cjs:11:54744
    at file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/@wasmer/sdk/0.4.1/dist/Library.cjs:11:1275
    at Object.next (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/@wasmer/sdk/0.4.1/dist/Library.cjs:11:1380)
    at file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/@wasmer/sdk/0.4.1/dist/Library.cjs:11:296
    at new Promise (<anonymous>)
    at A (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/@wasmer/sdk/0.4.1/dist/Library.cjs:11:41)
```

**Comment by sigmaSd** [comment]
The current state:
```ts
import { init, Wasmer } from "npm:@wasmer/sdk@0.9.0";

await init();

const pkg = await Wasmer.fromRegistry("python/python");
const instance = await pkg.entrypoint.run({
  args: ["-c", "print('Hello, World!')"],
});

const { code, stdout } = await instance.wait();
console.log(`Python exited with ${code}: ${stdout}`);
```

deno 2.1.4

```
error: Top-level await promise never resolved
const pkg = await Wasmer.fromRegistry("python/python");
```
