### ISSUE TITLE
demo is broken on https://webassembly.sh/

### ISSUE THREAD

**Issue by Kreijstal** [wasmerio/wasmer-js#433]
![grafik](https://github.com/user-attachments/assets/d98ec199-0227-47cf-ba9f-17b36331f547)
Using firefox on windows 10. Cowsay does not work.

![grafik](https://github.com/user-attachments/assets/6a863bde-9077-4bca-9b50-30387008b7a6)

**Comment by syrusakbary** [comment]
Hey @Kreijstal, we recommend using https://wasmer.sh/ for now.

You can run any package using: `wasmer run`.

Eg: `wasmer run cowsay hi`

**Comment by Kreijstal** [comment]
> Hey @Kreijstal, we recommend using https://wasmer.sh/ for now.
> 
> You can run any package using: `wasmer run`.
> 
> Eg: `wasmer run cowsay hi`

It worked, kind of?

```
bash-5.1# cowsay hi
bash: cowsay: command not found
bash-5.1# wasmer run cowsay hi
 ____
< hi >
 ----
bash-5.1# wasmer run cowsay hello
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 64)', library/std/src/io/stdio.rs:1008:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
bash-5.1# wasmer run cowsay hi   
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 64)', library/std/src/io/stdio.rs:1008:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
bash-5.1# wasmer run cowsay hi
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 64)', library/std/src/io/stdio.rs:1008:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
bash-5.1# RUST_BACKTRACE=1 wasmer run cowsay hi
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 64)', library/std/src/io/stdio.rs:1008:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
bash-5.1# 
```
