### ISSUE TITLE
init() - doesnt work, undici fetch failed.

### ISSUE THREAD

**Issue by ambrt** [wasmerio/wasmer-js#442]
Basically empty script with just `init()` doesn't work.

```
import { init } from "@wasmer/sdk";

async function run() {
  await init();

}
run();
```

Throws `undici` error.
```
> wasmer-sdk-node-example@0.0.0 run
> node example.mjs

node:internal/deps/undici/undici:13178
      Error.captureStackTrace(err);
            ^

TypeError: fetch failed
    at node:internal/deps/undici/undici:13178:13
    at async v_ (file:///home/user/wasmer/examples/node_modules/@wasmer/sdk/dist/index.mjs:11:47648)
    at async R_ (file:///home/user/wasmer/examples/node_modules/@wasmer/sdk/dist/index.mjs:11:48139)
    at async run (file:///home/user/wasmer/examples/example.mjs:26:3) {
  [cause]: Error: not implemented... yet...
      at makeNetworkError (node:internal/deps/undici/undici:8961:35)
      at schemeFetch (node:internal/deps/undici/undici:10356:34)
      at node:internal/deps/undici/undici:10205:26
      at mainFetch (node:internal/deps/undici/undici:10224:11)
      at fetching (node:internal/deps/undici/undici:10172:7)
      at fetch (node:internal/deps/undici/undici:10041:20)
      at fetch (node:internal/deps/undici/undici:13176:10)
      at fetch (node:internal/bootstrap/web/exposed-window-or-worker:72:12)
      at v_ (file:///home/user/wasmer/examples/node_modules/@wasmer/sdk/dist/index.mjs:11:46947)
      at R_ (file:///home/user/wasmer/examples/node_modules/@wasmer/sdk/dist/index.mjs:11:48145)
}

Node.js v23.2.0

```

It  related to https://github.com/nodejs/undici/issues/2751

**Comment by syrusakbary** [comment]
What version of Node are you using @ambrt ?

**Comment by syrusakbary** [comment]
To future readers, this is how to init wasmer-js in node:

```js
import { init } from "@wasmer/sdk/node";

async function run() {
  await init();

}
run();
```

**Comment by elya5** [comment]
I tried the import in an electron application with your code snippet but it fails:
```
App threw an error during load
Error [ERR_REQUIRE_ESM]: require() of ES Module project/node_modules/@wasmer/sdk/dist/node.mjs not supported.
Instead change the require of project/node_modules/@wasmer/sdk/dist/node.mjs to a dynamic import() which is available in all CommonJS modules.
    at c._load (node:electron/js2c/node_init:2:16955)
    at Object.<anonymous> (project/out/main/index.js:5:14)
A JavaScript error occurred in the main process
Uncaught Exception:
Error [ERR_REQUIRE_ESM]: require() of ES Module project/node_modules/@wasmer/sdk/dist/node.mjs not supported.
Instead change the require of project/node_modules/@wasmer/sdk/dist/node.mjs to a dynamic import() which is available in all CommonJS modules.
    at c._load (node:electron/js2c/node_init:2:16955)
    at Object.<anonymous> (project/out/main/index.js:5:14)
```

Is there anything else to consider when importing/running it?
